### ISSUE TITLE
Doesn't work on RubyMotion 5.3 OSX without a bit of hacking

### ISSUE THREAD

**Issue by bbugh** [jbender/motion-spec#12]
I'm making an OSX project, and am so grateful to have `expect` syntax after untraining using `should`, thanks for that. Unfortunately, I can't get it to run without doing some hacking.

The first error is:

```
Bundler::GemRequireError: There was an error while trying to load the gem 'motion-spec'.
Gem Load Error is: undefined method `main_cpp_file_txt' for class `Motion::Project::IOSConfig'
```

So I went to `Motion::Project::IOSConfig` in `motion-spec.rb` and commented out the `IOSConfig` class patch. The gem loaded fine, but then when running the test, I just saw two Bacon errors, and then the specs never ran, and it would sit until I sent a break:

```
2017-10-23 19:14:57.859 TestApp[874:1669360] +[Bacon run]: unrecognized selector sent to class 0x1005ce520
2017-10-23 19:14:57.860 TestApp[874:1669360] +[Bacon run]: unrecognized selector sent to class 0x1005ce520
```

Then I went and commented out that whole monkeypatch section, and everything seems to be working fine now. I'd make a PR but I don't know the repercussions of just hacking out some code that looks important. I don't know what the use case for that is, but it doesn't seem to be working anymore.

**Comment by jbender** [comment]
Hey there @bbugh, thanks for your interest in the project! I haven't done any RubyMotion work in about a year now, so I can't really vouch for the necessity of that monkeypatch anymore, except that it was definitely necessary "back in the day". I'd welcome a PR that validates the existence of the txt file (which has probably been removed in later versions of RM) and only patches it if it's found.

**Comment by bbugh** [comment]
Thanks for the reply! Seems like nobody else is using RubyMotion either. :) All of the projects are "5 years ago". I think yours is the most recently updated I've seen... 

For this issue, there were two problems:

1. I was doing `require 'motion-spec'` inside the App definition, instead of before (so I could only load it in test mode... oh well). 
2. Changing IOSConfig to OSXConfig made it work for me as expected. RubyMotion's load system is different from Ruby so I couldn't get it to dynamically choose to extend the right class. The best I could come up with was checking for `const_defined?`, which isn't the DRYest code.

```ruby
    if const_defined?('IOSConfig')
      class IOSConfig
        alias_method :old_main_cpp_file_txt, :main_cpp_file_txt

        def main_cpp_file_txt(spec_objs)
          old_main_cpp_file_txt(spec_objs).gsub(/Bacon/, 'MotionSpec')
        end
      end
    end

    if const_defined?('OSXConfig')
      class OSXConfig
        alias_method :old_main_cpp_file_txt, :main_cpp_file_txt

        def main_cpp_file_txt(spec_objs)
          old_main_cpp_file_txt(spec_objs).gsub(/Bacon/, 'MotionSpec')
        end
      end
    end
```

The rest of the code still seems to work properly, it was just a load error and class name error. I can make a PR for that if you'd like.
